name: elisysxui
description: xui projet 0.0.1

# version: 1.0.2
#homepage: https://elisys.netlify.com/
#author: gauthier.desomer@gmail.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  html: ^0.15.0
  js: ^0.6.3
  #yamlicious: ^0.1.0
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.1
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
  lint: ^1.0.0